version: '2'
services:
  db:
    container_name: portus_db
    image: percona:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "Wehausito$"
  portus:
    image: eugenmayer/portus:2.2.0
    container_name: portus
    build:
      context: .
    environment:
      PORTUS_DEBUG: 'true'
      #PORTUS_CREATE_CERT: 'false'
      PORTUS_ADMIN_PASSWORD: 'adminadminadmin'
      REGISTRY_SSL_ENABLED: 'true'
      REGISTRY_HOSTNAME: registry.dev
      REGISTRY_PORT: 443
      REGISTRY_NAME: Registry
      PORTUS_MACHINE_FQDN: portus.dev
      PORTUS_PORT: 443
      PORTUS_PRODUCTION_HOST: db
      PORTUS_PRODUCTION_DATABASE: portus
      PORTUS_PRODUCTION_USERNAME: root
      PORTUS_PRODUCTION_PASSWORD: "Wehausito$"
      PORTUS_DEVELOPMENT_HOST: db
      PORTUS_DEVELOPMENT_DATABASE: portus
      PORTUS_DEVELOPMENT_USERNAME: root
      PORTUS_DEVELOPMENT_PASSWORD: "Wehausito$"
      PORTUS_GRAVATAR_ENABLED: 'true'
      PORTUS_DELETE_ENABLED: 'true'
      PORTUS_KEY_PATH: /certs/privkey.pem
      PORTUS_CRT_PATH: /certs/fullchain.pem
      PORTUS_PASSWORD: "Wehausito$"
      PORTUS_SECRET_KEY_BASE: something
      PORTUS_CHECK_SSL_USAGE_ENABLED: 'true'
      PORTUS_EMAIL_SMTP_ENABLED: 'false'
      PORTUS_EMAIL_SMTP_ADDRESS: 'smtp.example.com'
      PORTUS_EMAIL_SMTP_PORT: 587
      PORTUS_EMAIL_SMTP_USER_NAME: 'username@example.com'
      PORTUS_EMAIL_SMTP_PASSWORD: 'password'
      PORTUS_EMAIL_SMTP_DOMAIN: 'example.com'
      PORTUS_LDAP_ENABLED: 'false'
      PORTUS_LDAP_HOSTNAME: ""
      PORTUS_LDAP_PORT: ""
      PORTUS_LDAP_METHOD: ""
      PORTUS_LDAP_BASE: ""
      PORTUS_LDAP_UID: cn
      PORTUS_LDAP_AUTHENTICATION_ENABLED: ""
      PORTUS_LDAP_AUTHENTICATION_BIND_DN: ""
      PORTUS_LDAP_AUTHENTICATION_PASSWORD: ""
      PORTUS_LDAP_GUESS_EMAIL_ENABLED: 'true'
      PORTUS_LDAP_GUESS_EMAIL_ATTR: mail
      PORTUS_REGISTRY_JWT_EXPIRATION_TIME_VALUE: 30
      RAILS_ENV: 'development'
    volumes:
      - ./test/certs:/certs
    depends_on:
      - db
      - registry
    external_links:
      - "nginx:registry.dev"
  registry:
    image: registry:2.6.2
    container_name: registry
    environment:
      # we can use environment variables to configure registry, see https://github.com/docker/distribution/blob/master/configuration/configuration.go#L13
      REGISTRY_LOG_LEVEL: warn
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_REALM: https://portus.dev/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: registry.dev
      REGISTRY_AUTH_TOKEN_ISSUER: portus.dev
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/fullchain.pem
      REGISTRY_HTTP_SECRET: somethingother
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://portus:3000/v2/webhooks/events
          timeout: 5000ms
          threshold: 2
          backoff: 20s

    volumes:
      - ./test/certs:/certs
    external_links:
      - "nginx:portus.dev"
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./test/portus.dev.conf:/etc/nginx/conf.d/portus.dev.conf
      - ./test/registry.dev.conf:/etc/nginx/conf.d/registry.dev.conf
      - /etc/letsencrypt/live/registry.wehaus.com/:/certs
    depends_on:
      - portus
      - registry
    ports:
      - "443:443"
    external_links:
      - "portus:portus.dev"
      - "registry:registry.dev"
